---
# tasks file for add_user
- name: Add user test
  user: 
    name: ans
    create_home: true
    groups: " {{ sudoGroup  }} " 
    shell: /bin/bash
    password: "{{ vaulted_password | password_hash('sha512') }}"
    update_password: on_create
# Add ssh keys    
- name: Add SSH keys to remote hosts
  copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=0400
		-"id_rsa.pub"

