---
# tasks file for add_user
- name: Add user test
  user: 
    name: test 
    groups: sudo 
    shell: /bin/bash
    password: "{{ vaulted_password | password_hash('sha512') }}"
    update_password: on_create

