version: '3.7'
services:
#Контейнер с PHP, назовём его app
      app:
# Если нет секции build, то система будет искать образ в
       build: ${PWD}/fpm/
# имя будущего образа
       image: app1/php
# имя контейнера после запуска
       container_name: app1
# монтируемая папка в контейнер
       volumes:
            - ${PWD}/test:/data
# мы можем создать для контейнеров внутреннюю сеть
       networks:
            - app-network
#контейнер с Nginx
      webserver:
        build: ${PWD}/nginx/
        image: app1/nginx
        container_name: webserver
        volumes:
          - ${PWD}/test:/data
# проброс портов
        ports:
          - "80:80"
          - "443:443"
        networks:
          - app-network
 # контейнер с MySQL
 # строим на базе стандартного образа
      db:
       image: mysql:5.7.22
       container_name: db
       ports:
          - "3306:3306"
# описываем, какую БД мы создаем
       environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       volumes:
            - ${PWD}/dbdata:/var/lib/mysql
       networks:
            - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge

