---
- hosts: server3
  remote_user: dima
  become: yes
  tasks:
    - name: Copy_config
      copy:
        src: /home/dima/new_configs/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: 0660

    - name: Restart service elasticsearch 
      service:
        name: elasticsearch
        state: restarted
        enabled: true
